### ISSUE TITLE
Grant by password

### ISSUE THREAD

**Issue by linking12** [newnil/oauth2-family-barrel#5]
如果是使用密码来授权的话，会报错
请求：
curl -d "grant_type=password" \
-d "client_id=test_password_client" \
-d "client_secret=1234567" \
-d "username=admin" \
-d "password=admin888" \
http://localhost:8082/security/oauth/token

结果：
 "timestamp" : 1490855234454,
  "status" : 401,
  "error" : "Unauthorized",
  "message" : "Full authentication is required to access this resource",
  "path" : "/security/oauth/token"
}

**Comment by dewafer** [comment]
如果我没记错的话，访问`/security/oauth/token`这个endpoint需要使用silent_id + client_secret作为basic认证的头才能过访问
