### ISSUE TITLE
授权登录进去之后，点击GetData就报错

### ISSUE THREAD

**Issue by dingyiming** [newnil/oauth2-family-barrel#6]
![image](https://cloud.githubusercontent.com/assets/12537013/25427561/92a9db98-2aa5-11e7-9fba-0c6e33bdb276.png)
![image](https://cloud.githubusercontent.com/assets/12537013/25427574/97c7d09e-2aa5-11e7-8e71-c9c2ee86195c.png)

**Comment by dewafer** [comment]
按照说明文档上的启动了3个服务了么？
