### ISSUE TITLE
401 on resource

### ISSUE THREAD

**Issue by prediator** [newnil/oauth2-family-barrel#7]
I switched to the production environment and on accessing the resource i get

**On web**
There was an unexpected error (type=Internal Server Error, status=500).
500 null

**Server Console log**
o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@3639c16d

org.springframework.web.client.HttpServerErrorException: 500 null

**Resource Console log**
org.springframework.web.client.HttpClientErrorException: 401 null

Can any one help me on this.

**Comment by dewafer** [comment]
The information you provided is not enough to tell what's the cause, and I think question like this belongs to stackoverflow.com, plz post it one the stackoverflow  thx.
